ALLOWED_TYPE_OF_RETRIEVALS= ['RAG', 'CRAG']
TYPE_OF_RETRIEVAL=ALLOWED_TYPE_OF_RETRIEVALS[0]
USE_REMOTE_LLM = True
REMOTE_LLM_NAME = "gpt-5"
REMOTE_API_KEY = "aa-FESyHjpBwExGgvfC9NwfrSuTWehTLPawZLNWYeiZY83uVqqN"